services:
  django:
    build: /opt/atlassian/pipelines/agent/build/
    command: gunicorn config.wsgi:application --bind 0.0.0.0:5555 --workers 3
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/trusted_routes_db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - /src/config/envs/.env.prod
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trusted_routes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
